---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.1
  - name: centos-6.6
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]

suites:
- name: default
  run_list:
    - recipe[nvm_test::default]
- name: nvm_install
  run_list:
    - recipe[nvm_test::nvm_install]
- name: nvm_alias_default
  run_list:
    - recipe[nvm_test::nvm_alias_default]
- name: nvm_source_install
  run_list:
    - recipe[nvm_test::nvm_install_from_source]
